[versions]
kotlin = "1.6.20-M1"
androidGradleVersion = "7.3.0-alpha03"
nexusPublish = "1.1.0"
versionChecker = "0.39.0"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradleVersion" }

[plugins]
#kotlinGradlePlugin = { id = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
#androidGradlePlugin = { id = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
nexus-publish = { id = "io.github.gradle-nexus:publish-plugin", version.ref = "nexusPublish" }
versionChecker = { id = "com.github.ben-manes.versions", version.ref = "versionChecker" }